//
//  LoRADeltaParityTests.swift
//  ltx-video-swift-mlx
//
//  Validates that our Swift LoRA delta computation matches Python PEFT
//  on a specific high-stakes layer: `audio_to_video_attn.to_q` block 0.
//
//  Hypothesis #2 from the LipDub debug plan: the cross-modal layer's
//  LoRA fusion direction may be wrong. We compare element-wise.
//
//  Reference Python output is at /tmp/lora_compare/python_a2v_to_q_block0_delta.safetensors
//  (generated by /tmp/lora_compare/inspect_lora.py). Test is skipped if missing.
//

import Testing
import Foundation
@preconcurrency import MLX
@testable import LTXVideo

@Suite("LoRA delta parity (audio_to_video_attn.to_q block 0)")
struct LoRADeltaParityTests {

    @Test func swiftDeltaMatchesPythonPEFT() throws {
        let pyPath = "/tmp/lora_compare/python_a2v_to_q_block0_delta.safetensors"
        let loraPath = "/Users/vincent/Pictures/FluxforgeStudio/Models/ltx-lora-lipdub/ltx-2.3-22b-ic-lora-lipdub-0.9.safetensors"

        guard FileManager.default.fileExists(atPath: pyPath) else {
            print("[SKIP] \(pyPath) missing — run /tmp/lora_compare/inspect_lora.py first")
            return
        }
        guard FileManager.default.fileExists(atPath: loraPath) else {
            print("[SKIP] LipDub LoRA missing at \(loraPath)")
            return
        }

        // Load Python's reference delta
        let pyData = try MLX.loadArrays(url: URL(fileURLWithPath: pyPath))
        guard let pyDelta = pyData["delta"] else {
            print("[SKIP] python delta not found in safetensors")
            return
        }
        let pyShape = pyDelta.shape
        print("[PY] delta shape \(pyShape)")
        #expect(pyShape == [2048, 4096], "Python delta should be (out=2048, in=4096)")

        // Load our LoRA via LoRALoader
        let config = LoRAConfig(weightsPath: loraPath, scale: 1.0)
        let weights = try LoRALoader.load(from: loraPath, config: config)
        print("[Swift] loaded LoRA: \(weights.layers.count) layer-pairs")

        let targetKey = "diffusion_model.transformer_blocks.0.audio_to_video_attn.to_q"
        guard let layer = weights.layers.first(where: { $0.originalKey == targetKey }) else {
            let candidates = weights.layers
                .map { $0.originalKey }
                .filter { $0.contains("audio_to_video_attn.to_q") && $0.contains("blocks.0") }
            print("[FAIL] layer \(targetKey) not found. Candidates: \(candidates.prefix(5))")
            #expect(Bool(false), "target layer not found in LoRA")
            return
        }
        print("[Swift] target layer: rank=\(layer.rank), alpha=\(String(describing: layer.alpha)), effectiveScale=\(layer.effectiveScale)")

        guard let swiftDelta = weights.getDelta(for: targetKey) else {
            #expect(Bool(false), "getDelta returned nil for target layer")
            return
        }
        let swiftDeltaF32 = swiftDelta.asType(.float32)
        MLX.eval(swiftDeltaF32)
        print("[Swift] delta shape: \(swiftDeltaF32.shape)")
        #expect(swiftDeltaF32.shape == pyShape, "Swift delta shape mismatch")

        // Element-wise diff
        let diff = MLX.abs(swiftDeltaF32 - pyDelta)
        MLX.eval(diff)
        let maxAbs = diff.max().item(Float.self)
        let meanAbs = diff.mean().item(Float.self)
        let pyMaxAbs = MLX.abs(pyDelta).max().item(Float.self)

        print("[RESULT] max |swift - python| = \(maxAbs)")
        print("[RESULT] mean |swift - python| = \(meanAbs)")
        print("[RESULT] python max |delta|  = \(pyMaxAbs)  → relative max diff = \(maxAbs / pyMaxAbs)")

        // Tolerance: bfloat16 round-trip noise is ~3e-3 relative.
        // We expect <1e-4 absolute since both sides should be bit-identical
        // up to bfloat16 rounding (Python keeps bf16 then casts to f32; Swift loads bf16 cast to f32).
        #expect(maxAbs < 1e-4, "Swift LoRA delta diverges from Python PEFT (max abs diff \(maxAbs))")
    }
}
